### ISSUE TITLE
Heroku button deploy broken

### ISSUE THREAD

**Issue by Rydgel** [Algomancer/Full-Stack-Scala-Starter#4]
<img width="469" alt="capture d ecran 2016-10-06 a 09 55 21" src="https://cloud.githubusercontent.com/assets/6583/19144640/1453c842-8bab-11e6-927c-4cbbb16f4563.png">

According to Heroku the name inside app.json might be too big.

**Comment by Algomancer** [comment]
Yep cheers, gotta fix the Heroku build. I'll remove the deploy button for now.
