### ISSUE TITLE
IDEA import the project, can't review the project structure tree

### ISSUE THREAD

**Issue by aniude** [Algomancer/Full-Stack-Scala-Starter#5]
![2016-10-25 17 21 34](https://cloud.githubusercontent.com/assets/1137266/19680234/862ca91c-9ad7-11e6-9314-87d18a5e6ba4.png)

Is that anything error? All of the file directory is invisible.

**Comment by PhilAndrew** [comment]
IntelliJ IDEA is not able to load this build.sbt because of this line

`onLoad in Global := (Command.process("project server", _: State)) compose (onLoad in Global).value`

I commented out the line then import, it can import then. Then I remove the comment and bring it back in after import.
